Repository Gijol/gijol-frontend, pull requests merged in 2022-05, with the labels that each got.

#10 File add
  .eslintrc.js
  package-lock.json
  package.json
  src/pages/frames/frame1/buttonBox/buttons.tsx
  src/pages/frames/frameExplain/styles.ts
  src/pages/frames/frameFileAdd/dragDrop/dragDrop.tsx
  src/pages/frames/frameFileAdd/dragDrop/styles.ts
  src/pages/frames/frameFileAdd/fildAdd.tsx
  src/pages/frames/mainPage/mainPageComponent.tsx
  src/pages/main.tsx
  src/pages/styles.ts
Labels: enhancement

#11 메인페이지 파일 업로드 구현 완료
  src/App.css
  src/assets/title.ts
  src/common/header/styles.ts
  src/img/question.png
  src/pages/frames/frame1/frame1.tsx
  src/pages/frames/frameExplain/Explanation.tsx
  src/pages/frames/frameFileAdd/buttonContainer/buttonContainer.tsx
  src/pages/frames/frameFileAdd/buttonContainer/helpToggle.tsx
  src/pages/frames/frameFileAdd/buttonContainer/style.ts
  src/pages/frames/frameFileAdd/dragDrop/dragDrop.tsx
  src/pages/frames/frameFileAdd/dragDrop/styles.ts
  src/pages/frames/frameFileAdd/fildAdd.tsx
  src/pages/frames/frameFileAdd/select/major.ts
  src/pages/frames/frameFileAdd/select/majorOptions.ts
  src/pages/frames/frameFileAdd/select/selectBox.tsx
  src/pages/frames/mainPage/mainPageComponent.tsx
  src/pages/styles.ts
Labels: enhancement

#16 feat: 결과 페이지로 result를 이동시킨다.
  src/App.tsx
  src/pages/frames/frameFileAdd/fildAdd.tsx
  src/pages/frames/frameFileAdd/pushBtnApi.ts
  src/pages/result.tsx
  src/utils/apiCall.ts
Labels: enhancement

#17 refactor: 로딩창 나오는 오류 해결
  src/pages/frames/frameFileAdd/fildAdd.tsx
Labels: bug

#20 Feature/second page
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/pages/frames/frame1/frame1.tsx
  src/pages/frames/frame1/styles.ts
  src/pages/frames/frameFileAdd/buttonContainer/style.ts
  src/pages/frames/frameFileAdd/fildAdd.tsx
  src/pages/frames/frameFileAdd/pushBtnApi.ts
  src/pages/frames/frameFileAdd/styles.ts
  src/pages/result.tsx
  src/pages/results/resultMainPage.tsx
  src/pages/styles.ts
  src/utils/api/basic.ts
  src/utils/api/call/pushBtnApi.ts
  src/utils/api/course.ts
  src/utils/api/header/etcMandatory.ts
  src/utils/api/header/humanities.ts
  src/utils/api/header/languageBasic.ts
  src/utils/api/header/major.ts
  src/utils/api/header/otherUncheckedClass.ts
  src/utils/api/header/scienceBasic.ts
  src/utils/api/result.ts
  src/utils/api/takenCourse.ts
  src/utils/baseApi.ts
Labels: bug

#30 Result page test2
  package-lock.json
  src/components/progressBars/CicularProgressWithLabel.tsx
  src/components/progressBars/styles.css
  src/pages/results/frameOverall/Overall.tsx
  src/pages/results/frameOverall/styles.css
  src/pages/results/frameSpecific/MenuResult/CourseList/CourseList.tsx
  src/pages/results/frameSpecific/MenuResult/CourseList/styles.css
  src/pages/results/frameSpecific/MenuResult/MenuResult.tsx
  src/pages/results/frameSpecific/MenuResult/SpecificProgress/SpecificBarProgress.tsx
  src/pages/results/frameSpecific/MenuResult/SpecificProgress/SpecificCircleProgress.tsx
  src/pages/results/frameSpecific/MenuResult/styles.ts
  src/pages/results/frameSpecific/MenuSelect/styles.ts
  src/pages/results/frameSpecific/styles.css
Labels: enhancement

#32 Result page test2
  src/pages/results/frameSpecific/MenuResult/CourseList/CourseList.tsx
  src/pages/results/frameSpecific/MenuResult/CourseList/styles.css
  src/pages/results/frameSpecific/MenuResult/MenuResult.tsx
Labels: enhancement

#35 feat: API 학점 반영하기
  src/pages/results/frameSpecific/Specific.tsx
Labels: enhancement

#36 feat: overall 및 specific 그래프 api 연동
  src/components/progressBars/LinearProgressWithLabel.tsx
  src/pages/result.tsx
  src/pages/results/frameOverall/Overall.tsx
  src/pages/results/frameSpecific/MenuResult/MenuResult.tsx
  src/pages/results/frameSpecific/MenuResult/SpecificProgress/SpecificBarProgress.tsx
  src/pages/results/frameSpecific/MenuResult/SpecificProgress/SpecificCircleProgress.tsx
  src/pages/results/frameSpecific/Specific.tsx
Labels: enhancement

#37 Result page test4
  src/pages/results/frameSpecific/MenuResult/CourseList/CourseList.tsx
  src/pages/results/frameSpecific/MenuResult/CourseList/styles.css
  src/pages/results/frameSpecific/MenuResult/MenuResult.tsx
  src/pages/results/frameSpecific/MenuResult/SpecificProgress/SpecificBarProgress.tsx
  src/pages/results/frameSpecific/Specific.tsx
  src/utils/api/course.ts
  src/utils/api/result.ts
Labels: enhancement

#39 feat : 지졸 모바일 페이지를 제작한다 👍
  src/App.tsx
  src/common/container/container.tsx
  src/common/title/title.ts
  src/pages/main.tsx
  src/pages/mobile/mobileContainer/moblieContainer.ts
  src/pages/mobile/mobileFrame/mobileIntroduce.tsx
  src/pages/mobile/mobileMain.tsx
  src/pages/results/frameOverall/Overall.tsx
  src/pages/results/frameRecommend/Recommend.tsx
  src/pages/results/frameRecommend/recommendBox/recommendBox.tsx
  src/pages/results/frameRecommend/recommendBox/styles.ts
  src/pages/results/frameSpecific/Specific.tsx
  src/pages/results/resultMainPage.tsx
Labels: enhancement

#42 Result page test4
  src/assets/img/explainPic1.png
  src/assets/img/explainPic2.png
  src/assets/img/explainPic3.png
  src/assets/img/explainPic4.png
  src/components/progressBars/CicularProgressWithLabel.tsx
  src/components/progressBars/LinearProgressWithLabel.tsx
  src/components/progressBars/styles.css
  src/pages/frames/frameExplain/explainPic/explainPic.tsx
  src/pages/frames/frameExplain/explainPic/styled.ts
  src/pages/frames/frameExplain/styles.ts
  src/pages/frames/frameFileAdd/fildAdd.tsx
  src/pages/frames/frameFileAdd/styles.ts
  src/pages/results/frameSpecific/MenuResult/CourseList/styles.css
  src/pages/results/frameSpecific/Specific.tsx
Labels: enhancement

#50 feat: 그림설명 문구 추가 및 메인페이지 css 통일
  src/common/title/title.ts
  src/pages/frames/frameExplain/Explanation.tsx
  src/pages/frames/frameExplain/explainDrawer/drawer.tsx
  src/pages/frames/frameExplain/explainDrawer/styles.ts
  src/pages/frames/frameExplain/styles.ts
  src/pages/frames/frameFileAdd/buttonContainer/style.ts
  src/pages/frames/frameFileAdd/fildAdd.tsx
  src/pages/frames/frameFileAdd/select/styles.ts
  src/pages/frames/frameFileAdd/styles.ts
  src/pages/results/frameOverall/styles.css
Labels: enhancement

#51 feat: 사진 변경 및 ZEUS 링크 추가
  src/assets/img/explainPic4.png
  src/pages/frames/frameExplain/explainDrawer/drawer.tsx
  src/pages/frames/frameFileAdd/buttonContainer/style.ts
Labels: enhancement

#52 feat: swiper부분 반응형으로 제작
  src/pages/results/frameRecommend/Recommend.tsx
  src/pages/results/frameRecommend/recommendBox/recommendBox.tsx
  src/pages/results/frameRecommend/recommendBox/styles.ts
  src/pages/results/frameRecommend/styles.css
Labels: enhancement

#58 feat: 추천 메세지 아래에서 뜨는 오류 해결
  src/components/progressBars/LinearProgressWithLabel.tsx
  src/pages/results/frameRecommend/Recommend.tsx
  src/pages/results/frameRecommend/recommendBox/styles.ts
  src/pages/results/frameSpecific/MenuSelect/Select.tsx
  src/pages/results/frameSpecific/MenuSelect/styles.ts
  src/pages/results/frameSpecific/Specific.tsx
Labels: enhancement, invalid

#62 Result page test4
  src/common/header/styles.ts
  src/pages/frames/frameFileAdd/buttonContainer/style.ts
  src/pages/result.tsx
  src/pages/results/frameOverall/Overall.tsx
  src/pages/results/frameRecommend/Recommend.tsx
  src/pages/results/frameRecommend/recommendBox/recommendBox.tsx
  src/pages/results/frameRecommend/recommendBox/styles.ts
  src/pages/results/frameSpecific/MenuResult/CourseList/CourseList.tsx
  src/pages/results/frameSpecific/MenuResult/MenuResult.tsx
  src/pages/results/frameSpecific/MenuSelect/Select.tsx
  src/pages/results/frameSpecific/Specific.tsx
  src/utils/api/course.ts
Labels: bug, enhancement
